server:
  port: 8088
spring:
  application:
    name: ms-bank
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: user
    password: user
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibername:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  level:
    root: info